-- *******************************************************
--  Auto-generated SQL from Excel questionnaire
--  Source file : Questionnaire.xlsx
--  Generated   : 2025-05-11 10:16:33
--  Script      : excel_to_sql.py
-- *******************************************************

INSERT INTO questions (id, TYPE, category, sequence_number, image_source, options_structure)
VALUES ('welcome', 'info_screen', 'intro', 10, 'welcoming', '{"showOnce": true}'),
       ('about_this_study', 'info_screen', 'intro', 20, 'questions', '{"showOnce": true}'),
       ('consent', 'info_screen', 'intro', 30, 'contract', '{"showOnce": true, "buttonText": "general.agree"}'),
       ('notifications', 'info_screen', 'intro', 40, 'reminders', '{"showOnce": true, "action": "request_notification_permission", "buttonText": "general.ok"}'),
       ('location_acces', 'info_screen', 'intro', 50, 'my-current-location', '{"showOnce": true, "action": "request_location_permission", "buttonText": "general.ok"}'),
       ('info_questions_about_you', 'info_screen', 'demographic', 100, 'thoughts', '{"showOnce": true}'),
       ('age_group', 'single_choice', 'demographic', 110, NULL, '{"showOnce": true, "autoAdvance": true, "options": [{"value": "age_group_under_16"}, {"value": "age_group_1625"}, {"value": "age_group_2635"}, {"value": "age_group_3645"}, {"value": "age_group_4655"}, {"value": "age_group_5665"}, {"value": "age_group_6675"}, {"value": "age_group_75"}]}'),
       ('sex', 'single_choice', 'demographic', 120, NULL, '{"showOnce": true, "autoAdvance": true, "options": [{"value": "sex_male"}, {"value": "sex_female"}, {"value": "sex_inter"}]}'),
       ('gender', 'single_choice', 'demographic', 130, NULL, '{"showOnce": true, "autoAdvance": true, "options": [{"value": "gender_female"}, {"value": "gender_male"}, {"value": "gender_nonbinary_genderqueer"}, {"value": "gender_trans_woman"}, {"value": "gender_trans_man"}, {"value": "gender_agender"}, {"value": "gender_inter"}, {"value": "gender_other"}]}'),
       ('sexual_orientation', 'single_choice', 'demographic', 140, NULL, '{"showOnce": true, "autoAdvance": true, "options": [{"value": "sexual_orientation_straight"}, {"value": "sexual_orientation_homosexual"}, {"value": "sexuql_orientation_bisexual"}, {"value": "sexual_orientation_pansexual"}, {"value": "sexual_orientation_asexual"}, {"value": "sexual_orientation_queer"}, {"value": "sexual_orientation_other"}]}'),
       ('education', 'single_choice', 'demographic', 150, NULL, '{"showOnce": true, "autoAdvance": true, "options": [{"value": "education_none"}, {"value": "education_secondary_school"}, {"value": "education_vocational_training_or_apprenticeship"}, {"value": "education_maturafmshms_or_equivalent"}, {"value": "education_university_of_applied_sciences_fhhf"}, {"value": "education_university_degree"}]}'),
       ('household_members', 'single_choice', 'demographic', 160, NULL, '{"showOnce": true, "autoAdvance": true, "options": [{"value": "household_members_1_living_alone"}, {"value": "household_members_2"}, {"value": "household_members_3"}, {"value": "household_members_4"}, {"value": "household_members_5"}, {"value": "household_members_6"}, {"value": "household_members_7"}, {"value": "household_members_8"}, {"value": "household_members_9"}, {"value": "household_members_10_or_more"}]}'),
       ('household_members_financing', 'single_choice', 'demographic', 170, NULL, '{"showOnce": true, "autoAdvance": true, "options": [{"value": "household_members_financing_1_person_myself_only"}, {"value": "household_members_financing_2"}, {"value": "household_members_financing_3"}, {"value": "household_members_financing_4"}, {"value": "household_members_financing_5"}, {"value": "household_members_financing_6"}, {"value": "household_members_financing_7"}, {"value": "household_members_financing_8"}, {"value": "household_members_financing_9"}, {"value": "household_members_financing_10_or_more"}]}'),
       ('monthly_household_income', 'single_choice', 'demographic', 180, NULL, '{"showOnce": true, "autoAdvance": true, "options": [{"value": "monthly_household_income_less_than_chf_1500"}, {"value": "monthly_household_income_chf_15003000"}, {"value": "monthly_household_income_chf_30004500"}, {"value": "monthly_household_income_chf_45006000"}, {"value": "monthly_household_income_chf_60007500"}, {"value": "monthly_household_income_chf_750010000"}, {"value": "monthly_household_income_more_than_chf_10000"}, {"value": "monthly_household_income_unknown"}]}'),
       ('employment_status', 'multiple_choice', 'demographic', 190, NULL, '{"showOnce": true, "options": [{"value": "employment_status_pupil__student"}, {"value": "employment_status_employed"}, {"value": "employment_status_selfemployed"}, {"value": "employment_status_retired"}, {"value": "employment_status_unemployed"}]}'),
       ('disabilities', 'single_choice', 'demographic', 200, NULL, '{"showOnce": true, "autoAdvance": true, "options": [{"value": "disabilities_yes"}, {"value": "disabilities_no"}]}'),
       ('different_country_than_born_in', 'single_choice', 'demographic', 210, NULL, '{"showOnce": true, "autoAdvance": true, "options": [{"value": "different_country_than_born_in_yes"}, {"value": "different_country_than_born_in_no"}]}'),
       ('axis_of_opression', 'multiple_choice', 'intersection', 220, NULL, '{"showOnce": true, "options": [{"value": "axis_of_opression_yes_because_of_my_gender"}, {"value": "axis_of_opression_yes_because_of_my_age"}, {"value": "axis_of_opression_yes_because_of_my_background"}, {"value": "axis_of_opression_yes_because_of_my_skin_colour_or_appearance"}, {"value": "axis_of_opression_yes_because_of_my_language_or_accent"}, {"value": "axis_of_opression_yes_because_of_my_social_or_financial_situation"}, {"value": "axis_of_opression_yes_because_of_my_clothing_or_style"}, {"value": "axis_of_opression_yes_because_of_my_sexual_orientation"}, {"value": "axis_of_opression_yes_because_of_my_health_condition_or_a_disability"}, {"value": "axis_of_opression_yes_for_another_reason"}, {"value": "axis_of_opression_no"}]}'),
       ('info_current_location', 'info_screen', 'place', 500, 'our-neighborhood', NULL),
       ('indoors_outdoors', 'single_choice', 'place', 510, NULL, '{"autoAdvance": true, "options": [{"value": "indoors_outdoors_indoors"}, {"value": "indoors_outdoors_outdoors"}]}'),
       ('location_category', 'multiple_choice', 'place', 520, NULL, '{"options": [{"value": "location_category_at_home"}, {"value": "location_category_at_someone_elses_home"}, {"value": "location_category_workplace"}, {"value": "location_category_school__university"}, {"value": "location_category_shopping_or_services"}, {"value": "location_category_café__restaurant__bar"}, {"value": "location_category_leisure_or_sports_facility"}, {"value": "location_category_park_or_green_space"}, {"value": "location_category_cultural_or_religious_place"}, {"value": "location_category_health_or_therapy_setting"}, {"value": "location_category_on_the_move_walking_cycling_driving"}, {"value": "location_category_public_transport"}, {"value": "location_category_other_place"}]}'),
       ('people_with_you', 'multiple_choice', 'place', 530, NULL, '{"options": [{"value": "people_with_you_no_one"}, {"value": "people_with_you_partner"}, {"value": "people_with_you_children"}, {"value": "people_with_you_family"}, {"value": "people_with_you_friends"}, {"value": "people_with_you_colleagues"}, {"value": "people_with_you_acquaintances"}, {"value": "people_with_you_animalspets"}, {"value": "people_with_you_strangers"}, {"value": "people_with_you_other"}]}'),
       ('activity', 'multiple_choice', 'place', 540, NULL, '{"options": [{"value": "activity_leisure_or_relaxation"}, {"value": "activity_travelling_or_commuting"}, {"value": "activity_working_or_studying"}, {"value": "activity_shopping_or_running_errands"}, {"value": "activity_housework_or_tidying_up"}, {"value": "activity_cooking_or_eating"}, {"value": "activity_care_responsibilities"}, {"value": "activity_social_activities"}, {"value": "activity_using_media"}, {"value": "activity_resting_or_sleeping"}, {"value": "activity_other"}]}'),
       ('environment_noise', 'slider', 'place', 550, NULL, NULL),
       ('environment_nature', 'slider', 'place', 560, NULL, NULL),
       ('environment_lively', 'slider', 'place', 570, NULL, NULL),
       ('environmen_pleasure', 'slider', 'place', 580, NULL, NULL),
       ('info_wellbeing', 'info_screen', 'well-being', 700, 'relaxation', NULL),
       ('general_wellbeing', 'slider', 'well-being', 710, NULL, NULL),
       ('content', 'slider', 'well-being', 720, NULL, NULL),
       ('tense_relaxed', 'slider', 'well-being', 730, NULL, NULL),
       ('awake', 'slider', 'well-being', 740, NULL, NULL),
       ('sense_of_belonging', 'slider', 'intersection', 900, NULL, NULL),
       ('factors_sense_of_belonging', 'multiple_choice', 'intersection', 910, NULL, '{"options": [{"value": "factors_sense_of_belonging_yes_because_of_my_gender"}, {"value": "factors_sense_of_belonging_yes_because_of_my_age"}, {"value": "factors_sense_of_belonging_yes_because_of_my_background"}, {"value": "factors_sense_of_belonging_yes_because_of_my_skin_colour_or_appearance"}, {"value": "factors_sense_of_belonging_yes_because_of_my_language_or_accent"}, {"value": "factors_sense_of_belonging_yes_because_of_my_social_or_financial_situation"}, {"value": "factors_sense_of_belonging_yes_because_of_my_clothing_or_style"}, {"value": "factors_sense_of_belonging_yes_because_of_my_sexual_orientation"}, {"value": "factors_sense_of_belonging_yes_because_of_my_health_condition_or_a_disability"}, {"value": "factors_sense_of_belonging_yes_for_another_reason"}, {"value": "factors_sense_of_belonging_no"}]}'),
       ('majority_comparison', 'multiple_choice', 'intersection', 920, NULL, '{"options": [{"value": "majority_comparison_in_my_gender"}, {"value": "majority_comparison_in_my_age"}, {"value": "majority_comparison_in_my_background"}, {"value": "majority_comparison_in_my_skin_colour_or_appearance"}, {"value": "majority_comparison_in_my_language_or_accent"}, {"value": "majority_comparison_in_my_social_or_financial_situation"}, {"value": "majority_comparison_in_my_clothing_or_style"}, {"value": "majority_comparison_in_my_sexual_orientation"}, {"value": "majority_comparison_in_my_health_condition_or_a_disability"}, {"value": "majority_comparison_alone"}]}'),
       ('other_factors_negative', 'text', 'intersection', 930, NULL, NULL),
       ('other_factors_positive', 'text', 'intersection', 940, NULL, NULL);