INSERT INTO questions (id, type, category, sequence_number, image_source, options_structure) VALUES
('welcome', 'info_screen', 'first-info', 10, 'welcoming', '{"showOnce": true}'),
('about_this_study', 'info_screen', 'first-info', 20, 'questions', '{"showOnce": true}'),
('consent', 'info_screen', 'first-info', 30, 'contract', '{"showOnce": true, "buttonText": "general.agree"}'),
('notifications', 'info_screen', 'first-info', 40, 'reminders', '{"showOnce": true, "buttonText": "general.ok", "action": "request_notification_permission"}'),
('location_acces', 'info_screen', 'first-info', 50, 'my-current-location', '{"showOnce": true, "buttonText": "general.ok", "action": "request_location_permission"}'),
('info_questions_about_you', 'info_screen', 'personal_data', 100, 'thoughts', '{"showOnce": true}'),
('age_group', 'single_choice', 'personal_data', 110, NULL, '{"autoAdvance": true, "showOnce": true, "options": [{"value": "age_group_under_16"}, {"value": "age_group_1625"}, {"value": "age_group_2635"}, {"value": "age_group_3645"}, {"value": "age_group_4655"}, {"value": "age_group_5665"}, {"value": "age_group_6675"}, {"value": "age_group_75"}]}'),
('gender', 'single_choice', 'personal_data', 120, NULL, '{"autoAdvance": true, "showOnce": true, "options": [{"value": "gender_female"}, {"value": "gender_male"}, {"value": "gender_nonbinary"}, {"value": "gender_trans"}, {"value": "gender_intersex"}, {"value": "gender_other"}, {"value": "gender_prefer_not_to_say"}]}'),
('education', 'single_choice', 'personal_data', 130, NULL, '{"autoAdvance": true, "showOnce": true, "options": [{"value": "education_no_diploma_or_certificate"}, {"value": "education_vocational_training_or_apprenticeship"}, {"value": "education_maturafmshms_or_equivalent"}, {"value": "education_university_of_applied_sciences_fhhf"}, {"value": "education_university_degree"}]}'),
('household_members', 'single_choice', 'personal_data', 140, NULL, '{"autoAdvance": true, "showOnce": true, "options": [{"value": "household_members_1_living_alone"}, {"value": "household_members_2"}, {"value": "household_members_3"}, {"value": "household_members_4"}, {"value": "household_members_5"}, {"value": "household_members_6"}, {"value": "household_members_7"}, {"value": "household_members_8"}, {"value": "household_members_9"}, {"value": "household_members_10_or_more"}]}'),
('household_members_financing', 'single_choice', 'personal_data', 150, NULL, '{"autoAdvance": true, "showOnce": true, "options": [{"value": "household_members_financing_1_person_myself_only"}, {"value": "household_members_financing_2_people"}, {"value": "household_members_financing_3_people"}, {"value": "household_members_financing_4_people"}, {"value": "household_members_financing_5_people"}, {"value": "household_members_financing_6_people"}, {"value": "household_members_financing_7_people"}, {"value": "household_members_financing_8_people"}, {"value": "household_members_financing_9_people"}, {"value": "household_members_financing_10_or_more"}]}'),
('monthly_household_income', 'single_choice', 'personal_data', 160, NULL, '{"autoAdvance": true, "showOnce": true, "options": [{"value": "monthly_household_income_less_than_chf_1500"}, {"value": "monthly_household_income_chf_15003000"}, {"value": "monthly_household_income_chf_30004500"}, {"value": "monthly_household_income_chf_45006000"}, {"value": "monthly_household_income_chf_60007500"}, {"value": "monthly_household_income_chf_750010000"}, {"value": "monthly_household_income_more_than_chf_10000"}, {"value": "monthly_household_income_dont_know"}]}'),
('employment_status', 'multiple_choice', 'personal_data', 170, NULL, '{"showOnce": true, "options": [{"value": "employment_status_pupil__student"}, {"value": "employment_status_employed"}, {"value": "employment_status_selfemployed"}, {"value": "employment_status_retired"}, {"value": "employment_status_unemployed"}]}'),
('disabilities', 'single_choice', 'personal_data', 180, NULL, '{"autoAdvance": true, "showOnce": true, "options": [{"value": "disabilities_yes"}, {"value": "disabilities_no"}]}'),
('different_country_than_born_in', 'single_choice', 'personal_data', 190, NULL, '{"autoAdvance": true, "showOnce": true, "options": [{"value": "different_country_than_born_in_yes"}, {"value": "different_country_than_born_in_no"}]}'),
('axis_of_opression', 'multiple_choice', 'personal_data', 200, NULL, '{"showOnce": true, "options": [{"value": "axis_of_opression_yes_because_of_my_skin_colour_or_appearance"}, {"value": "axis_of_opression_yes_because_of_my_name_or_language"}, {"value": "axis_of_opression_yes_because_of_my_religion_or_background"}, {"value": "axis_of_opression_yes_for_another_reason"}, {"value": "axis_of_opression_no"}]}'),
('info_current_location', 'info_screen', 'location', 500, 'our-neighborhood', NULL),
('indoors_outdoors', 'single_choice', 'location', 510, NULL, '{"autoAdvance": true, "options": [{"value": "indoors_outdoors_indoors"}, {"value": "indoors_outdoors_outdoors"}]}'),
('location_category', 'single_choice', 'location', 520, NULL, '{"autoAdvance": true, "options": [{"value": "location_category_at_home"}, {"value": "location_category_at_someone_elses_home"}, {"value": "location_category_workplace"}, {"value": "location_category_school__university"}, {"value": "location_category_shopping_or_services"}, {"value": "location_category_café__restaurant__bar"}, {"value": "location_category_leisure_or_sports_facility"}, {"value": "location_category_park_or_green_space"}, {"value": "location_category_cultural_or_religious_place"}, {"value": "location_category_health_or_therapy_setting"}, {"value": "location_category_on_the_move_walking_cycling_driving"}, {"value": "location_category_public_transport"}, {"value": "location_category_other_place"}]}'),
('people_with_you', 'multiple_choice', 'location', 530, NULL, '{"options": [{"value": "people_with_you_no_one"}, {"value": "people_with_you_partner"}, {"value": "people_with_you_children"}, {"value": "people_with_you_family"}, {"value": "people_with_you_friends"}, {"value": "people_with_you_colleagues"}, {"value": "people_with_you_acquaintances"}, {"value": "people_with_you_animalspets"}, {"value": "people_with_you_strangers"}, {"value": "people_with_you_other"}]}'),
('activity', 'multiple_choice', 'location', 540, NULL, '{"options": [{"value": "activity_leisure_or_relaxation"}, {"value": "activity_travelling_or_commuting"}, {"value": "activity_working_or_studying"}, {"value": "activity_shopping_or_running_errands"}, {"value": "activity_housework_or_tidying_up"}, {"value": "activity_cooking_or_eating"}, {"value": "activity_care_responsibilities"}, {"value": "activity_social_activities"}, {"value": "activity_using_media"}, {"value": "activity_resting_or_sleeping"}, {"value": "activity_other"}]}'),
('surroundings_attributes', 'multiple_choice', 'location', 550, NULL, '{"options": [{"value": "surroundings_attributes_heavy_traffic_or_noise"}, {"value": "surroundings_attributes_pleasant_soundscape"}, {"value": "surroundings_attributes_visible_nature_or_greenery"}, {"value": "surroundings_attributes_high_diversity_of_natural_elements"}, {"value": "surroundings_attributes_crowds_or_lively_atmosphere"}, {"value": "surroundings_attributes_quiet_environment_few_people"}, {"value": "surroundings_attributes_pleasant_temperature"}, {"value": "surroundings_attributes_unpleasant_temperature"}, {"value": "surroundings_attributes_good_air_quality"}, {"value": "surroundings_attributes_poor_air_quality"}, {"value": "surroundings_attributes_nice_view"}, {"value": "surroundings_attributes_unpleasant_surroundings"}]}'),
('surroundings_state', 'multiple_choice', 'location', 560, NULL, '{"options": [{"value": "surroundings_state_lively_and_busy"}, {"value": "surroundings_state_few_people_calm_atmosphere"}, {"value": "surroundings_state_i_meet_familiar_people_here"}, {"value": "surroundings_state_the_space_is_pleasantly_designed"}, {"value": "surroundings_state_conversations_are_easy_here"}, {"value": "surroundings_state_i_feel_safe_here"}, {"value": "surroundings_state_the_place_is_clean"}, {"value": "surroundings_state_the_place_is_easily_accessible"}, {"value": "surroundings_state_there_are_plants_or_greenery_in_the_space"}, {"value": "surroundings_state_water_is_visible_nearby_eg_river_pond"}, {"value": "surroundings_state_pleasant_natural_light_eg_sunlight_through_windows"}, {"value": "surroundings_state_pleasant_artificial_lighting_eg_colours_arrangement_of_lights"}, {"value": "surroundings_state_there_are_places_to_sit_eg_benches_chairs"}, {"value": "surroundings_state_pleasant_sounds_or_music"}]}'),
('info_well-being', 'info_screen', 'well-being', 700, 'relaxation', NULL),
('wellbeing_general', 'slider', 'well-being', 710, NULL,
 '{"values": ["Very unwell", "Neutral", "Very well"]}'),

-- Contentment
('wellbeing_content', 'slider', 'well-being',   720, NULL,
 '{"values": ["Very discontent", "Neutral", "Very content"]}'),

-- Tension/Relaxation
('wellbeing_relaxation', 'slider', 'well-being', 730, NULL,
 '{"values": ["Very tense", "Neutral", "Very relaxed"]}'),

-- Wakefulness
('wellbeing_awake', 'slider', 'well-being', 740, NULL,
 '{"values": ["Very tired", "Neutral", "Very awake"]}'),

-- Belonging
('wellbeing_belonging', 'slider', 'environment', 750, NULL,
 '{"values": ["Very out of place", "Neutral", "Very much at home"]}'),

('factors_sense_of_belonging', 'multiple_choice', 'well-being', 760, NULL, '{"options": [{"value": "factors_sense_of_belonging_yes_because_of_my_gender"}, {"value": "factors_sense_of_belonging_yes_because_of_my_age"}, {"value": "factors_sense_of_belonging_yes_because_of_my_background"}, {"value": "factors_sense_of_belonging_yes_because_of_my_skin_colour_or_appearance"}, {"value": "factors_sense_of_belonging_yes_because_of_my_language_or_accent"}, {"value": "factors_sense_of_belonging_yes_because_of_my_social_or_financial_situation"}, {"value": "factors_sense_of_belonging_yes_because_of_my_clothing_or_style"}, {"value": "factors_sense_of_belonging_yes_because_of_my_sexual_orientation"}, {"value": "factors_sense_of_belonging_yes_because_of_my_health_condition_or_a_disability"}, {"value": "factors_sense_of_belonging_yes_for_another_reason"}, {"value": "factors_sense_of_belonging_no"}]}'),
('other_factors', 'text', 'well-being', 770, NULL, '{"options": [{"value": "other_factors_open_text_entry"}]}');